add Skellington to Case Model
ONSdigital/census-rm-action-worker pull request #14
Opened 2020-03-20 10:52 UTC by LukeLoze1

# Motivation and Context:
skellington cases

# What has changed?
Added Skellington case to Case Entity

# How to test?
mvn clean install, then test with other branches on the ticket

# Links:
https://trello.com/b/yarvSxGu/census-2021-response-management

2020-03-25 13:39 UTC, hbrace approved these changes

2020-03-27 09:40 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/action/model/entity/Case.java
> +  private boolean skellington;
It's spelled _skeleton_

2020-03-27 09:40 UTC, NickGrantX requested changes
Save your typos for PRs. Keep the code & database searchable for people looking for _skeleton_ cases.

2020-03-30 08:08 UTC, NickGrantX approved these changes
LGTM 👍

2020-03-30 11:03 UTC, merged