Add createdDateTime and lastUpdated fields
ONSdigital/census-rm-action-worker pull request #35
Opened 2020-06-18 15:15 UTC by LeoKHoward

# Motivation and Context
New fields in CASE_UPDATED and CASE_CREATED events

# What has changed
New fields added

# How to test?
Build other repos on card and run ATs

# Links
https://trello.com/c/n6FwePKv/1052-waiting-on-action-processor-casecreated-caseupdated-events-should-contain-the-createddatetime-field-5

https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CATD&title=Response+Management+Event+Dictionary

2020-06-18 15:20 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [caseCreated/caseUpdated events should contain the createdDateTime field (5)](https://trello.com/c/n6FwePKv/1052-casecreated-caseupdated-events-should-contain-the-createddatetime-field-5)

2020-06-18 15:21 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [caseCreated/caseUpdated events should contain the createdDateTime field (5)](https://trello.com/c/n6FwePKv/1052-casecreated-caseupdated-events-should-contain-the-createddatetime-field-5)

2020-06-19 07:57 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/action/model/entity/Case.java
> +import javax.persistence.Entity;
something has gone wrong with code formatting here

2020-06-19 07:57 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/action/model/entity/Case.java
> +import org.hibernate.annotations.*;
more code formatting problems

2020-06-19 07:58 UTC, NickGrantX requested changes
Something weird going on with your code formatter. Are you running the `fmt:fmt` Maven plugin before commit & push?

2020-06-19 11:45 UTC, AdamHawtin requested changes
Test failures in the travis build

2020-06-22 09:51 UTC, AdamHawtin approved these changes
👍 Building fine locally for me now

2020-06-22 10:00 UTC, NickGrantX approved these changes

2020-06-23 06:44 UTC, merged