(IC03.1/IC04.1) Generate CE UNIT Addressed ICL Print Files
ONSdigital/census-rm-action-worker pull request #37
Opened 2020-06-26 09:23 UTC by LeoKHoward

# Motivation and Context
These ActionTypes needed to be changed to generate and address line for each instance of expected response recorded against the unit whereas before they were not dependent on expected capacity

# What has changed
ActionTypes added to appropriate class
Refactored method names

# How to test?
Build with other repos on card and run ATs

# Links
https://trello.com/c/FPqeHTfQ/1046-ic031-i041-generate-ce-unit-addressed-icl-print-files-3
https://collaborate2.ons.gov.uk/confluence/display/SDC/RM+Census+Initial+Contact+Run+Book+-+2021
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?pageId=34832584

2020-06-26 09:30 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [(IC03.1/IC04.1) Generate CE UNIT Addressed ICL Print Files (3)](https://trello.com/c/FPqeHTfQ/1046-ic031-ic041-generate-ce-unit-addressed-icl-print-files-3)

2020-06-26 12:03 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/action/builders/UacQidLinkBuilder.java
> +          // expected capacity for
formatting has made this quite ugly

2020-06-26 12:05 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/action/model/entity/ActionType.java
> +  CE_IC03_1(
These changes should be mirrored in Action Processor too

2020-06-26 12:06 UTC, NickGrantX requested changes
Minor comments, but Action Processor needs the ActionType changes too

2020-06-29 11:07 UTC, ryangrundy7 approved these changes

2020-06-29 11:09 UTC, NickGrantX approved these changes

2020-06-29 11:46 UTC, merged