Address frame delta - Allow user-defined where clause for action rules
ONSdigital/census-rm-action-worker pull request #40
Opened 2020-07-01 10:36 UTC by liamtoozer

# Motivation and Context:

We can now create action rules using a String which should resemble the end of a WHERE clause in SQL, e.g. `AND treatment_code IN ('abc', 'def')`. 

# What has changed?

* Renamed classifier and changed type

# How to test?

See other related PRs

# Links:

https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13

2020-07-01 10:37 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Address Frame Delta - generate additional initial contact files (13)](https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13)

2020-07-03 11:39 UTC, AdamHawtin approved these changes

2020-07-07 07:44 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/action/model/entity/ActionRule.java
> +  private String userDefinedWhereClause;
as mentioned on other ticket, it's not 'user defined'... it's a classifier [fragment].

2020-07-07 07:45 UTC, NickGrantX requested changes
Comment similar to one on other PR

2020-07-07 13:04 UTC, NickGrantX approved these changes

2020-07-08 07:47 UTC, merged